USE opstrax;

INSERT INTO companies (name,status,owner,metric,priority,location) VALUES
('OpsTrax Logistics','Active','Enterprise Admin','Primary tenant','Healthy','Chicago HQ'),('Northstar Retail Distribution','Active','Customer Success','Customer tenant','Healthy','Dallas HQ');
INSERT INTO roles (name,status,owner,metric,priority,location) VALUES
('Administrator','Active','Security','Full access','Healthy','Global'),('Dispatcher','Active','Operations','Dispatch access','Healthy','Global'),('Driver','Active','Fleet','Mobile access','Healthy','Global'),('Mechanic','Active','Maintenance','Shop access','Healthy','Global'),('Customer','Active','Portal','ETA access','Healthy','Global');
INSERT INTO users (company_id,role_id,email,password_hash,name,status,owner,metric,priority,location) VALUES
(1,1,'admin@opstrax.com','Admin@12345','Avery Stone','Active','Security','Enterprise administrator','Healthy','Chicago HQ'),
(1,2,'dispatcher@opstrax.com','Admin@12345','Maya Chen','Active','Operations','Senior dispatcher','Healthy','Control Tower'),
(1,3,'driver@opstrax.com','Admin@12345','Luis Ortega','Active','Fleet','Driver mobile profile','Healthy','Terminal 3'),
(1,4,'mechanic@opstrax.com','Admin@12345','Sam Patel','Active','Maintenance','Lead mechanic','Healthy','Shop A'),
(2,5,'customer@opstrax.com','Admin@12345','Jordan Lee','Active','Portal','Customer ETA user','Healthy','Dallas HQ');

INSERT INTO vehicles (name,status,owner,metric,priority,location,vin,odometer) VALUES
('Vehicle 101','Active','Maya Chen','82% utilization','Normal','Chicago','VIN101',141200),('Vehicle 102','Active','Maya Chen','Idle 18 min','Warning','Milwaukee','VIN102',98220),('Vehicle 103','Maintenance Due','Sam Patel','PM due in 2 days','High','Shop A','VIN103',202881),('Vehicle 104','Active','Maya Chen','On route ORD-DET','Normal','Gary','VIN104',77310),('Vehicle 105','Delayed','Maya Chen','ETA risk 42 min','High','Toledo','VIN105',167420),('Vehicle 106','Active','Ops Control','Healthy telematics','Normal','Columbus','VIN106',118004),('Vehicle 107','Active','Ops Control','Cold chain stable','Normal','Indianapolis','VIN107',90992),('Vehicle 108','Active','Ops Control','High margin lane','Normal','St Louis','VIN108',225031),('Vehicle 109','Maintenance Due','Sam Patel','Brake inspection','High','Shop B','VIN109',184222),('Vehicle 110','Active','Ops Control','HOS compliant','Normal','Nashville','VIN110',76042),('Vehicle 111','Active','Ops Control','Trailer assigned','Normal','Louisville','VIN111',130004),('Vehicle 112','Critical','Sam Patel','Check engine fault','Critical','Cincinnati','VIN112',211540);
INSERT INTO drivers (name,status,owner,metric,priority,location,license_no,safety_score) VALUES
('Luis Ortega','Active','Maya Chen','Safety 96','Normal','Chicago','D101',96),('Nina Brooks','Active','Dispatch','Safety 91','Normal','Milwaukee','D102',91),('Ethan Reed','Coaching Review','Safety','Harsh braking trend','Warning','Toledo','D103',78),('Priya Shah','Active','Dispatch','On-time 94%','Normal','Columbus','D104',94),('Marcus Hill','Active','Dispatch','HOS 6.5h left','Normal','Gary','D105',88),('Tara Nguyen','Active','Dispatch','Top performer','Healthy','St Louis','D106',98),('Owen Ford','Active','Dispatch','ETA stable','Normal','Nashville','D107',90),('Rosa Diaz','At Stop','Dispatch','Dock 12','Normal','Dallas','D108',92),('Ben Carter','Delayed','Dispatch','Weather route','High','Cincinnati','D109',84),('Amara King','Active','Dispatch','Cross-dock','Normal','Louisville','D110',89),('Jon Bell','Active','Dispatch','New route','Normal','Detroit','D111',87),('Ivy Ross','Review','Safety','Camera event','Warning','Indianapolis','D112',80);
INSERT INTO assets (name,status,owner,metric,priority,location,asset_type) VALUES
('Trailer TR-301','Active','Fleet','53 ft dry van','Normal','Chicago','Trailer'),('Trailer TR-302','Active','Fleet','Reefer temp 36F','Normal','Milwaukee','Reefer'),('Chassis CH-88','Active','Fleet','Port ready','Normal','Gary','Chassis'),('Container CT-440','At Stop','Fleet','Loaded','Normal','Dallas','Container'),('Liftgate LG-14','Maintenance Due','Shop','Hydraulic check','High','Shop A','Equipment'),('Trailer TR-303','Active','Fleet','Assigned','Normal','St Louis','Trailer'),('Trailer TR-304','Delayed','Fleet','Dock congestion','Warning','Toledo','Trailer'),('Reefer RF-09','Critical','Fleet','Temp alarm','Critical','Columbus','Reefer');
INSERT INTO customers (name,status,owner,metric,priority,location,contact_email) VALUES
('Northstar Retail','Active','Sales','Gold SLA','Healthy','Dallas','ops@northstar.test'),('Pioneer Foods','Active','Sales','Cold chain','Normal','Chicago','logistics@pioneer.test'),('Atlas Manufacturing','Active','Sales','Dedicated lane','Normal','Detroit','ship@atlas.test'),('UrbanMed Supply','Warning','Sales','ETA sensitive','High','Columbus','ops@urbanmed.test'),('BrightBox Ecommerce','Active','Sales','High volume','Normal','Indianapolis','carrier@brightbox.test'),('CoreBuild Materials','Active','Sales','Flatbed demand','Normal','Louisville','dispatch@corebuild.test');
INSERT INTO contracts (name,status,owner,metric,priority,location,rate) VALUES
('Northstar Midwest Rate Card','Active','Finance','Margin 21%','Healthy','Dallas',2.81),('Pioneer Reefer Agreement','Renewal Review','Finance','Expires 45 days','Warning','Chicago',3.42),('Atlas Dedicated Lane','Active','Finance','Margin 18%','Normal','Detroit',2.65),('UrbanMed Expedited SLA','Active','Finance','Penalty exposure','High','Columbus',4.2);
INSERT INTO routes (name,status,owner,metric,priority,location,miles,eta) VALUES
('ORD to DET Corridor','Active','Planning','282 miles','Normal','Chicago',282,'6h 10m'),('MKE to STL Loop','Active','Planning','386 miles','Normal','Milwaukee',386,'7h 45m'),('DAL Medical Sprint','Warning','Planning','SLA tight','High','Dallas',144,'2h 55m'),('IND Crossdock Wave','Active','Planning','Multi-stop','Normal','Indianapolis',221,'5h 20m'),('CMH Retail Route','Delayed','Planning','Weather risk','High','Columbus',310,'7h 5m'),('LVI Backhaul','Active','Planning','Margin positive','Healthy','Louisville',198,'4h 10m'),('NSH Night Linehaul','Active','Planning','Driver swap','Normal','Nashville',410,'8h 20m'),('CIN Recovery Route','Critical','Planning','Vehicle fault','Critical','Cincinnati',112,'3h 0m');
INSERT INTO route_stops (route_id,name,status,owner,metric,priority,location,stop_order) SELECT ((n-1) % 8)+1, CONCAT('Stop ', n), IF(n % 5=0,'Delayed','Planned'), 'Planning', CONCAT('Window ', n), IF(n % 5=0,'High','Normal'), CONCAT('Dock ', n), n FROM (SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20) x;
INSERT INTO jobs (name,status,owner,metric,priority,location,customer_id,pickup_window,delivery_window) SELECT CONCAT('JOB-',1000+n), ELT((n % 6)+1,'Unassigned','Assigned','En Route','At Stop','Completed','Delayed / Exception'), 'Maya Chen', CONCAT('$', 850+n*37, ' revenue'), IF(n % 6=5,'High','Normal'), ELT((n % 6)+1,'Chicago','Milwaukee','Detroit','Dallas','Columbus','Cincinnati'), ((n-1)%6)+1, '08:00-10:00','14:00-18:00' FROM (SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25) x;
INSERT INTO dispatch_assignments (name,status,owner,metric,priority,location,job_id,vehicle_id,driver_id) VALUES
('JOB-1001 Dispatch','Unassigned','Maya Chen','Needs driver','High','Chicago',1,1,1),('JOB-1002 Dispatch','Assigned','Maya Chen','Vehicle 102','Normal','Milwaukee',2,2,2),('JOB-1003 Dispatch','En Route','Maya Chen','ETA 2h 12m','Normal','Detroit',3,3,3),('JOB-1004 Dispatch','At Stop','Maya Chen','Dock 8','Normal','Dallas',4,4,4),('JOB-1005 Dispatch','Completed','Maya Chen','POD received','Healthy','Columbus',5,5,5),('JOB-1006 Dispatch','Delayed / Exception','Maya Chen','Weather delay','High','Cincinnati',6,6,6),('JOB-1007 Dispatch','Assigned','Maya Chen','Ready','Normal','Indianapolis',7,7,7),('JOB-1008 Dispatch','En Route','Maya Chen','On schedule','Normal','St Louis',8,8,8);
INSERT INTO trips (name,status,owner,metric,priority,location,route_id) SELECT CONCAT('Trip ', id), status, owner, metric, priority, location, id FROM routes;
INSERT INTO location_events (name,status,owner,metric,priority,location,latitude,longitude) SELECT name,status,owner,metric,priority,location,41.8 + id/100, -87.6 - id/100 FROM vehicles;
INSERT INTO maintenance_items (name,status,owner,metric,priority,location,due_date) VALUES
('PM Vehicle 103','Due','Sam Patel','Oil and filters','High','Shop A',CURDATE()),('Brake inspection 109','Due','Sam Patel','Front axle','High','Shop B',CURDATE()),('Reefer service RF-09','Critical','Sam Patel','Temp fault','Critical','Columbus',CURDATE()),('Tire rotation 106','Scheduled','Shop','Next week','Normal','Shop A',DATE_ADD(CURDATE(),INTERVAL 7 DAY)),('DOT check 101','Scheduled','Shop','Due 14 days','Normal','Chicago',DATE_ADD(CURDATE(),INTERVAL 14 DAY)),('Battery test 112','Critical','Shop','Fault code','Critical','Cincinnati',CURDATE()),('Liftgate LG-14','Due','Shop','Hydraulic service','High','Shop A',CURDATE()),('Annual inspection 108','Scheduled','Shop','Calendar due','Normal','St Louis',DATE_ADD(CURDATE(),INTERVAL 21 DAY)),('Coolant 104','Scheduled','Shop','Preventive','Normal','Gary',DATE_ADD(CURDATE(),INTERVAL 10 DAY)),('Alignment 105','Due','Shop','Tire wear','High','Toledo',CURDATE());
INSERT INTO work_orders (name,status,owner,metric,priority,location,cost) VALUES
('WO-7001','Open','Sam Patel','Vehicle 112 diagnostics','Critical','Cincinnati',950),('WO-7002','In Progress','Sam Patel','Brake inspection','High','Shop B',640),('WO-7003','Completed','Sam Patel','Oil service','Healthy','Shop A',310),('WO-7004','Open','Sam Patel','Reefer sensor','Critical','Columbus',1220),('WO-7005','Scheduled','Sam Patel','Liftgate repair','High','Shop A',780),('WO-7006','Completed','Sam Patel','Battery replacement','Healthy','Shop A',410),('WO-7007','In Progress','Sam Patel','Tire set','High','Toledo',1600),('WO-7008','Scheduled','Sam Patel','DOT inspection','Normal','Chicago',280);
INSERT INTO fuel_transactions (name,status,owner,metric,priority,location,gallons,amount,idle_cost) VALUES
('Fuel TX 1','Paid','Finance','Vehicle 101','Normal','Chicago',92,386,24),('Fuel TX 2','Paid','Finance','Vehicle 102','Warning','Milwaukee',110,473,61),('Fuel TX 3','Paid','Finance','Vehicle 103','Normal','Gary',80,332,18),('Fuel TX 4','Review','Finance','Vehicle 105','High','Toledo',126,558,84),('Fuel TX 5','Paid','Finance','Vehicle 106','Normal','Columbus',75,319,20),('Fuel TX 6','Paid','Finance','Vehicle 107','Normal','Indianapolis',88,374,16),('Fuel TX 7','Review','Finance','Vehicle 108','Warning','St Louis',119,512,77),('Fuel TX 8','Paid','Finance','Vehicle 109','Normal','Shop B',66,286,11),('Fuel TX 9','Paid','Finance','Vehicle 110','Normal','Nashville',93,401,22),('Fuel TX 10','Paid','Finance','Vehicle 111','Normal','Louisville',81,342,20),('Fuel TX 11','Review','Finance','Vehicle 112','Critical','Cincinnati',135,612,96),('Fuel TX 12','Paid','Finance','Vehicle 104','Normal','Gary',74,315,14);
INSERT INTO safety_events (name,status,owner,metric,priority,location,event_type) SELECT CONCAT('Safety Event ', n), IF(n%5=0,'Review','Closed'), 'Safety Team', IF(n%3=0,'Harsh braking','Following distance'), IF(n%5=0,'High','Normal'), ELT((n%6)+1,'Chicago','Milwaukee','Detroit','Dallas','Columbus','Cincinnati'), 'camera' FROM (SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15) x;
INSERT INTO dashcam_events (name,status,owner,metric,priority,location,clip_url) SELECT CONCAT('Dashcam Clip ', n), IF(n%3=0,'Review','Processed'), 'AI Dashcam', IF(n%3=0,'Potential incident','No action'), IF(n%3=0,'High','Normal'), ELT((n%6)+1,'Chicago','Milwaukee','Detroit','Dallas','Columbus','Cincinnati'), 'demo://clip' FROM (SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8) x;
INSERT INTO compliance_documents (name,status,owner,metric,priority,location,expires_on) VALUES
('Insurance certificate','Warning','Compliance','Expires in 12 days','High','Carrier File',DATE_ADD(CURDATE(),INTERVAL 12 DAY)),('DOT authority','Active','Compliance','Current','Normal','Ops HQ',DATE_ADD(CURDATE(),INTERVAL 180 DAY)),('Driver medical card','Warning','Compliance','5 renewals due','High','Driver Files',DATE_ADD(CURDATE(),INTERVAL 20 DAY)),('Hazmat permit','Active','Compliance','Current','Normal','Ops HQ',DATE_ADD(CURDATE(),INTERVAL 120 DAY)),('IFTA filing','Warning','Compliance','Quarter close','High','Finance',DATE_ADD(CURDATE(),INTERVAL 10 DAY));
INSERT INTO inspections (name,status,owner,metric,priority,location,defects) VALUES ('DVIR 101','Passed','Luis Ortega','No defects','Healthy','Chicago',0),('DVIR 102','Defect Review','Nina Brooks','Marker light','Warning','Milwaukee',1),('DVIR 103','Failed','Ethan Reed','Brake issue','Critical','Shop A',2),('DVIR 104','Passed','Priya Shah','Clean','Healthy','Gary',0),('DVIR 105','Defect Review','Ben Carter','Tire wear','High','Toledo',1);
INSERT INTO hos_logs (name,status,owner,metric,priority,location,hours_remaining) VALUES ('HOS Luis','Active','ELD','6.5h left','Normal','Chicago',6.5),('HOS Nina','Warning','ELD','1.2h left','High','Milwaukee',1.2),('HOS Ethan','Active','ELD','4.4h left','Normal','Detroit',4.4),('HOS Priya','Active','ELD','7.1h left','Normal','Columbus',7.1),('HOS Marcus','Review','ELD','Potential violation','High','Gary',0.4);
INSERT INTO expenses (name,status,owner,metric,priority,location,amount) VALUES ('Toll batch','Approved','Finance','Midwest lanes','Normal','Chicago',420),('Hotel layover','Review','Finance','Weather exception','Warning','Toledo',189),('Scale ticket','Approved','Finance','JOB-1008','Normal','St Louis',22),('Repair invoice','Review','Finance','WO-7001','High','Cincinnati',950);
INSERT INTO carriers (name,status,owner,metric,priority,location,mc_number) VALUES ('BlueLine Carrier','Active','Carrier Ops','Score 94','Healthy','Chicago','MC1001'),('RapidRelay','Warning','Carrier Ops','Insurance review','High','Dallas','MC1002'),('Summit Freight','Active','Carrier Ops','Capacity 18 trucks','Normal','Denver','MC1003');
INSERT INTO documents (name,status,owner,metric,priority,location,doc_type) VALUES ('POD JOB-1005','Processed','Docs','Customer visible','Healthy','Columbus','POD'),('BOL JOB-1008','Active','Docs','In transit','Normal','St Louis','BOL'),('Claim packet','Review','Docs','Incident report','High','Cincinnati','Claim');
INSERT INTO sla_records (name,status,owner,metric,priority,location,score) VALUES ('Northstar SLA','Healthy','Customer Success','96% on-time','Healthy','Dallas',96),('UrbanMed SLA','Warning','Customer Success','Penalty risk','High','Columbus',84),('Pioneer SLA','Healthy','Customer Success','Cold chain stable','Healthy','Chicago',94);
INSERT INTO kpi_records (name,status,owner,metric,priority,location,category,label,value,target) VALUES
('Monday Ops','Healthy','Analytics','On-time trend','Normal','Ops HQ','weekly','Mon',42,39),('Tuesday Ops','Healthy','Analytics','On-time trend','Normal','Ops HQ','weekly','Tue',46,41),('Wednesday Ops','Warning','Analytics','Delay spike','High','Ops HQ','weekly','Wed',38,34),('Thursday Ops','Healthy','Analytics','Recovered','Normal','Ops HQ','weekly','Thu',51,48),('Friday Ops','Healthy','Analytics','Peak demand','Normal','Ops HQ','weekly','Fri',58,52),('Saturday Ops','Healthy','Analytics','Weekend','Normal','Ops HQ','weekly','Sat',33,31),('Sunday Ops','Healthy','Analytics','Weekend','Normal','Ops HQ','weekly','Sun',29,28);
INSERT INTO ai_insights (name,status,owner,metric,priority,location) VALUES
('Cost outlier detected','Active','OpsTrax AI','Vehicle 112 has 2.4x higher combined fuel and maintenance exposure.','High','Cincinnati'),('Driver coaching queue','Active','OpsTrax AI','Ethan Reed and Ivy Ross should receive camera-assisted coaching.','Warning','Safety Desk'),('Maintenance plan','Active','OpsTrax AI','Pull PM for 103 and brake inspection for 109 into tomorrow morning.','High','Shop A'),('SLA risk','Active','OpsTrax AI','UrbanMed expedited load has penalty exposure; assign highest availability vehicle.','High','Columbus'),('Fuel optimization','Active','OpsTrax AI','Reduce idling on vehicles 102, 105, 108, and 112.','Warning','Fuel Desk'),('Route margin','Active','OpsTrax AI','LVI backhaul route is margin positive and should be repeated.','Healthy','Planning'),('Compliance watch','Active','OpsTrax AI','Insurance and medical cards require action before month end.','Warning','Compliance'),('Dispatch recovery','Active','OpsTrax AI','CIN recovery route needs substitute vehicle after fault event.','Critical','Cincinnati'),('Carrier score','Active','OpsTrax AI','RapidRelay should be paused until insurance review clears.','High','Carrier Ops'),('Customer ETA','Active','OpsTrax AI','Push proactive ETA notification for JOB-1006.','Warning','Portal');
INSERT INTO notifications (name,status,owner,metric,priority,location) VALUES ('Vehicle fault','Open','Telemetry','Vehicle 112 check engine fault','Critical','Cincinnati'),('Weather delay','Open','Dispatch','JOB-1006 delayed 42 minutes','High','Toledo'),('Compliance warning','Open','Compliance','Insurance expires in 12 days','High','Ops HQ'),('HOS risk','Open','ELD','Nina Brooks 1.2h remaining','Warning','Milwaukee');
INSERT INTO audit_logs (name,status,owner,metric,priority,location,actor) SELECT CONCAT('Audit event ', n),'Recorded','Security', CONCAT('Operational change ', n),'Normal','OpsTrax', ELT((n%5)+1,'Avery Stone','Maya Chen','Sam Patel','System','Jordan Lee') FROM (SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20) x;
INSERT INTO integrations (name,status,owner,metric,priority,location,provider) VALUES ('Samsara Telematics','Connected','Integrations','Streaming every 30s','Healthy','Cloud','Samsara'),('Motive ELD','Connected','Integrations','HOS sync active','Healthy','Cloud','Motive'),('Fuelman','Warning','Integrations','Delayed file import','Warning','Cloud','Fuelman'),('QuickBooks','Connected','Integrations','Invoices synced','Healthy','Cloud','Intuit');
INSERT INTO subscription_plans (name,status,owner,metric,priority,location,monthly_price) VALUES ('OpsTrax Enterprise','Active','Billing','250 vehicles included','Healthy','Account',8999),('AI Safety Add-on','Active','Billing','Dashcam review included','Healthy','Account',1499),('Customer Portal Pack','Active','Billing','Unlimited ETA links','Healthy','Account',799);
