USE opstrax;

INSERT INTO command_center_actions (title, description, category, priority, status, linked_entity_type, linked_entity_id, owner_role, due_at) VALUES
('Review delayed JOB-1006', 'Weather and route congestion pushed JOB-1006 into exception status. Customer ETA update is required.', 'Review late job', 'Critical', 'Open', 'job', 6, 'Dispatcher', DATE_ADD(UTC_TIMESTAMP(), INTERVAL 30 MINUTE)),
('Create work order for Vehicle 112', 'Vehicle 112 has a critical diagnostic fault and high idle cost exposure.', 'Create work order', 'Critical', 'Open', 'vehicle', 12, 'Maintenance Manager', DATE_ADD(UTC_TIMESTAMP(), INTERVAL 1 HOUR)),
('Coach Ethan Reed', 'Driver has repeated harsh braking trend and camera review flags.', 'Coach driver', 'High', 'Open', 'driver', 3, 'Safety Manager', DATE_ADD(UTC_TIMESTAMP(), INTERVAL 4 HOUR)),
('Send UrbanMed ETA notice', 'UrbanMed expedited SLA is in watch status and needs proactive customer messaging.', 'Send customer ETA', 'High', 'Open', 'customer', 4, 'Customer Success', DATE_ADD(UTC_TIMESTAMP(), INTERVAL 45 MINUTE)),
('Review dashcam clip 6', 'Potential incident clip requires safety manager review and evidence disposition.', 'Review safety event', 'High', 'Acknowledged', 'dashcam_event', 6, 'Safety Manager', DATE_ADD(UTC_TIMESTAMP(), INTERVAL 2 HOUR)),
('Renew insurance certificate', 'Carrier insurance certificate expires in 12 days and is audit-visible.', 'Renew compliance document', 'High', 'Open', 'compliance_document', 1, 'Compliance Manager', DATE_ADD(UTC_TIMESTAMP(), INTERVAL 1 DAY)),
('Investigate Vehicle 108 fuel anomaly', 'Fuel spend and idle cost are both above expected lane baseline.', 'Investigate fuel anomaly', 'Medium', 'Open', 'vehicle', 8, 'Fleet Manager', DATE_ADD(UTC_TIMESTAMP(), INTERVAL 8 HOUR)),
('Resequence CMH retail route', 'Route delay risk can be reduced by moving Dock 5 ahead of Dock 7.', 'Review late job', 'Medium', 'Open', 'route', 5, 'Dispatcher', DATE_ADD(UTC_TIMESTAMP(), INTERVAL 3 HOUR)),
('Pull forward PM for Vehicle 103', 'Preventive maintenance due in two days should be advanced before long-haul assignment.', 'Create work order', 'Medium', 'Open', 'vehicle', 3, 'Mechanic', DATE_ADD(UTC_TIMESTAMP(), INTERVAL 12 HOUR)),
('Audit HOS warning for Nina Brooks', 'ELD shows 1.2 hours remaining and next dispatch assignment may create violation risk.', 'Review safety event', 'Medium', 'Open', 'driver', 2, 'Compliance Manager', DATE_ADD(UTC_TIMESTAMP(), INTERVAL 5 HOUR)),
('Validate RapidRelay insurance hold', 'Carrier score is constrained by insurance review status.', 'Renew compliance document', 'Low', 'Open', 'carrier', 2, 'Carrier Manager', DATE_ADD(UTC_TIMESTAMP(), INTERVAL 2 DAY)),
('Confirm POD workflow for JOB-1005', 'Completed job has proof-of-delivery available for customer portal publishing.', 'Send customer ETA', 'Low', 'Completed', 'job', 5, 'Dispatcher', DATE_ADD(UTC_TIMESTAMP(), INTERVAL 6 HOUR));

INSERT INTO operational_events (event_type, severity, title, description, linked_entity_type, linked_entity_id, occurred_at) VALUES
('vehicle_arrived','Healthy','Vehicle 104 arrived at Gary geofence','Vehicle 104 crossed the planned geofence and remains on time.','vehicle',4,DATE_SUB(UTC_TIMESTAMP(), INTERVAL 4 MINUTE)),
('job_delayed','High','JOB-1006 entered delay exception','Weather corridor and dock congestion pushed ETA beyond SLA tolerance.','job',6,DATE_SUB(UTC_TIMESTAMP(), INTERVAL 8 MINUTE)),
('route_deviated','Warning','CMH route deviated from planned corridor','Route 5 deviated around a delay zone near Columbus.','route',5,DATE_SUB(UTC_TIMESTAMP(), INTERVAL 13 MINUTE)),
('maintenance_warning','Critical','Vehicle 112 diagnostic fault active','Check engine fault requires recovery action and work order creation.','vehicle',12,DATE_SUB(UTC_TIMESTAMP(), INTERVAL 18 MINUTE)),
('driver_safety_event','High','Harsh braking event flagged','Safety review queue received repeat harsh braking pattern.','driver',3,DATE_SUB(UTC_TIMESTAMP(), INTERVAL 23 MINUTE)),
('eta_sent','Healthy','Customer ETA sent for JOB-1006','Portal notification sent with revised delivery window.','job',6,DATE_SUB(UTC_TIMESTAMP(), INTERVAL 29 MINUTE)),
('compliance_expiring','Warning','Insurance certificate expiring','Document expires in 12 days and is visible in audit queue.','compliance_document',1,DATE_SUB(UTC_TIMESTAMP(), INTERVAL 36 MINUTE)),
('work_order_created','Healthy','WO-7001 created','Diagnostic work order created for Vehicle 112.','work_order',1,DATE_SUB(UTC_TIMESTAMP(), INTERVAL 42 MINUTE)),
('vehicle_arrived','Healthy','Vehicle 107 arrived at Indianapolis crossdock','Cold chain remains stable.','vehicle',7,DATE_SUB(UTC_TIMESTAMP(), INTERVAL 48 MINUTE)),
('job_delayed','Warning','JOB-1012 SLA watch','Customer lane entered watch status from stop dwell.','job',12,DATE_SUB(UTC_TIMESTAMP(), INTERVAL 54 MINUTE)),
('route_deviated','Warning','Night linehaul rerouted','Driver swap route adjusted for HOS compliance.','route',7,DATE_SUB(UTC_TIMESTAMP(), INTERVAL 62 MINUTE)),
('maintenance_warning','High','Vehicle 109 brake inspection due','Brake inspection is due before next dispatch.','vehicle',9,DATE_SUB(UTC_TIMESTAMP(), INTERVAL 75 MINUTE)),
('driver_safety_event','Warning','Following distance event received','Camera AI marked event for coaching review.','driver',12,DATE_SUB(UTC_TIMESTAMP(), INTERVAL 82 MINUTE)),
('eta_sent','Healthy','ETA sent for Northstar delivery','Customer portal updated with accurate arrival window.','customer',1,DATE_SUB(UTC_TIMESTAMP(), INTERVAL 92 MINUTE)),
('compliance_expiring','Warning','Medical card renewals due','Five driver qualification files have renewal risk.','compliance_document',3,DATE_SUB(UTC_TIMESTAMP(), INTERVAL 105 MINUTE)),
('fuel_anomaly','High','Vehicle 108 fuel anomaly detected','Fuel spend above lane baseline with elevated idle time.','vehicle',8,DATE_SUB(UTC_TIMESTAMP(), INTERVAL 118 MINUTE)),
('vehicle_arrived','Healthy','Vehicle 111 arrived at Louisville terminal','Trailer handoff completed successfully.','vehicle',11,DATE_SUB(UTC_TIMESTAMP(), INTERVAL 132 MINUTE)),
('job_delayed','High','JOB-1018 delayed at stop','Dock dwell exceeded planned service window.','job',18,DATE_SUB(UTC_TIMESTAMP(), INTERVAL 145 MINUTE)),
('work_order_created','Healthy','WO-7007 tire set in progress','Maintenance team started tire replacement.','work_order',7,DATE_SUB(UTC_TIMESTAMP(), INTERVAL 158 MINUTE)),
('route_deviated','Warning','UrbanMed route resequenced','Expedited stop order changed to protect SLA.','route',3,DATE_SUB(UTC_TIMESTAMP(), INTERVAL 170 MINUTE)),
('maintenance_warning','Critical','RF-09 reefer temperature alarm','Reefer asset generated critical temperature alarm.','asset',8,DATE_SUB(UTC_TIMESTAMP(), INTERVAL 185 MINUTE)),
('driver_safety_event','High','Ivy Ross camera review opened','Dashcam clip requires safety disposition.','driver',12,DATE_SUB(UTC_TIMESTAMP(), INTERVAL 196 MINUTE)),
('eta_sent','Healthy','Pioneer Foods ETA sent','Cold chain shipment ETA published to portal.','customer',2,DATE_SUB(UTC_TIMESTAMP(), INTERVAL 210 MINUTE)),
('compliance_expiring','Warning','IFTA filing due soon','Quarter close filing requires finance review.','compliance_document',5,DATE_SUB(UTC_TIMESTAMP(), INTERVAL 225 MINUTE)),
('fuel_anomaly','Medium','Vehicle 102 high idle pattern','Idle time is above terminal staging baseline.','vehicle',2,DATE_SUB(UTC_TIMESTAMP(), INTERVAL 240 MINUTE));

INSERT INTO ai_recommendations (category, severity, title, insight, evidence_json, recommended_action, linked_entity_type, linked_entity_id, status) VALUES
('Risk detected','Critical','Vehicle 112 threatens dispatch continuity','Vehicle 112 has a critical diagnostic fault and active recovery-route dependency. This matters because it can strand the CIN recovery route and increase SLA exposure.', '{"sources":["vehicles","maintenance_items","work_orders"],"entities":["Vehicle 112","WO-7001"]}', 'Dispatch substitute vehicle and complete diagnostic work order within one hour.', 'vehicle', 12, 'Open'),
('Cost leakage','High','Idle cost increased materially today','Idle cost is concentrated on Vehicles 102, 105, 108, and 112. This matters because wait patterns are eroding lane margin before invoicing.', '{"sources":["fuel_transactions"],"idleCost":463,"vehicles":["Vehicle 102","Vehicle 105","Vehicle 108","Vehicle 112"]}', 'Review staging, detention, and driver wait patterns with dispatch.', 'vehicle', 112, 'Open'),
('Maintenance prediction','High','Maintenance risk is clustered in tractor and reefer assets','Critical and due maintenance items are concentrated around Vehicle 103, Vehicle 109, Vehicle 112, and RF-09.', '{"sources":["maintenance_items","assets"],"dueItems":4,"criticalItems":2}', 'Create or pull forward work orders before assigning long-haul work.', 'maintenance_item', 1, 'Open'),
('Driver coaching','High','Coaching queue should be prioritized','Ethan Reed and Ivy Ross show repeat safety review patterns. This matters because repeated camera events increase insurance and incident risk.', '{"sources":["drivers","safety_events","dashcam_events"],"drivers":["Ethan Reed","Ivy Ross"]}', 'Create coaching tasks and review dashcam evidence packages.', 'driver', 3, 'Open'),
('SLA/customer issue','High','UrbanMed SLA is in watch status','UrbanMed expedited load has penalty exposure and a delayed route context.', '{"sources":["customers","jobs","routes"],"customer":"UrbanMed Supply"}', 'Send proactive ETA and assign highest-availability vehicle.', 'customer', 4, 'Open'),
('Compliance warning','Warning','Documents require renewal before audit window','Insurance, medical cards, and IFTA filing are approaching expiration or review.', '{"sources":["compliance_documents"],"warnings":5}', 'Renew high-priority documents and record audit trail.', 'compliance_document', 1, 'Open'),
('Fuel anomaly','Medium','Vehicle 108 fuel spend exceeds lane baseline','Fuel transaction review suggests higher spend than expected for lane profile.', '{"sources":["fuel_transactions"],"vehicle":"Vehicle 108"}', 'Investigate fuel purchase and idling against route plan.', 'vehicle', 8, 'Open'),
('Dispatch optimization','Medium','CMH retail route can be resequenced','Stop order changes can reduce expected delay and protect SLA.', '{"sources":["routes","route_stops"],"route":"CMH Retail Route"}', 'Move high-risk dock stop earlier and notify customer success.', 'route', 5, 'Open'),
('Asset utilization','Medium','Reefer and trailer utilization has imbalance','Reefer risk and trailer assignments indicate underutilization in some assets.', '{"sources":["assets","jobs"],"assetTypes":["Reefer","Trailer"]}', 'Rebalance equipment assignments before next dispatch wave.', 'asset', 8, 'Open'),
('Executive summary','Watch','Today is in WATCH status','The operation is healthy overall but has delayed jobs, idle cost leakage, maintenance risk, and compliance warnings requiring action.', '{"sources":["dashboard","command_center_actions"],"status":"Watch"}', 'Work the critical and high-priority action queue first.', 'company', 1, 'Open');
