services:
  mysql:
    image: mysql:8.4
    container_name: vantelyx-clm-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: vantelyx_clm
      MYSQL_USER: vantelyx_user
      MYSQL_PASSWORD: vantelyx_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - vantelyx_mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  api:
    build:
      context: ./server/Vantelyx.Api
    container_name: vantelyx-clm-api
    restart: unless-stopped
    ports:
      - "8087:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Server=mysql;Port=3306;Database=vantelyx_clm;User=vantelyx_user;Password=vantelyx_password;
    depends_on:
      - mysql

  web:
    build:
      context: ./client
    container_name: vantelyx-clm-web
    restart: unless-stopped
    ports:
      - "9702:80"
    depends_on:
      - api

volumes:
  vantelyx_mysql_data:
